### PR TITLE
feat/edge-runtime

### PR DESCRIPTION
**Pull request by mattddean**

### CODE REVIEW

**Comment by abbaseya** [comment]
@mattddean tests seem to fail, have you managed to test these changes?

**Comment by abbaseya** [comment]
@mattddean note that the `http-client` favors `navigator.sendBeacon()` over `fetch` anyway, I like your approach for determining runtime, but it seems that nodejs builtin packages `url`, `http`, and `https` are not resolved this way, I remember trying something similar and failed, no idea why these 3 only works when defined at the root of the `http-client`!
If you can manage to understand why is that, it would be great of course.
My takeaway there is that you need to handle `edge` where both `window` and `navigator` are undefined while `fetch` is defined? I'm not sure that's the case, unless I am missing something.

**Comment by mattddean** [comment]
@abbaseya sorry for the delay. I will try to get back to this this week.

I started to investigate the issue, and I think it's related to the fact that newer versions of node.js include the `fetch` function.

So my first question to you is: if `fetch` is available, should we default to using that, or should we first detect if node.js is the runtime and use the https/http/url builtins?

**Comment by abbaseya** [comment]
@mattddean I think we should always check for `navigator.sendBeacon` first, if that not available, then check `fetch`, if that not available, we check `http(s)/url`

**Comment by abbaseya** [comment]
@mattddean you seem correct, I have pushed a simple tweak to your determine function so that it detect nodejs runtime first, then fallback to detecting browser, then edge. Will you confirm that the latest change works when you use edge?

**Comment by mattddean** [comment]
@abbaseya I'm not entirely sure what's going on, but I think I finally got it working. It has something to do with tests running in parallel on the same port. I'm sorry to have wiped out your last commit, but I'm happy to put it back if you don't like this approach.

The easiest way to test if it's working is to run in nodejs 18 to test fetch and then again in nodejs 16 to test the nodejs builtins.

Anyway, all of the API manager tests seem to pass at this point with and without fetch available. If you like this approach, we'll have to make the same updates to the rest of the tests.

**Comment by abbaseya** [comment]
@mattddean I have no preference regarding which approach you choose, but I see that you have commented out important parts of the api manager tests, basically that test is not expecting anything. My advice is to keep the tests the same.
On the other hand, earlier you mentioned that newer versions of nodejs having fetch available. That is indeed the problem, that's why you initial determineRuntime function was returning `edge` while the tests should return `nodejs`
So I guess you need to detect nodejs runtime before checking the fetch function, where fetch is defined at node v18
What do you think?

**Comment by mattddean** [comment]
@abbaseya I thought you said that we should use fetch if it's available, even if the runtime is nodejs.

**Comment by mattddean** [comment]
@abbaseya I have added back the api manager tests that I commented out. Do the rest of the test changes look good to you? I can make similar changes in the other test files.

**Comment by abbaseya** [comment]
@mattddean lookikg good so far, but I was mentioning these changes in particular:
https://github.com/convertcom/javascript-sdk/commit/865280e1222b42e831913a7e42dd621732c83e63

**Comment by abbaseya** [comment]
@mattddean I believe the question is that should we reply on `node-fetch` primarily in tests? Not sure if we should for the time being. Currently tests written assuming that in node env the SDK uses classic `http(s)/url` builtins, and expects responses accordingly. Switching to native node fetch requires re-writing all tests while requiring node v18+ to run the tests.
I'm not against that to be honest, but I think we should wait since node fetch is finally stable staring from node v21 (_that's very recent_). I expect many node-based projects still using older node versions.
That said, I believe your latest changes works perfectly addressing this case, I just restored api tests and configured QA tests for node v16 instead.
I'm going to merge this PR with a couple more fixes fir the next release, many thanks for your solid contribution 🙏🏻

**Review by abbaseya — APPROVED** [review]

**Comment by mattddean** [comment]
@abbaseya sounds good! Only warning I would give you is that the way the code is written, if fetch is available (if the user is running the code on 17.5+), that's what's going to get used by api-manager. If you're comfortable with that, this seems great! Thanks for all your help!

**Comment by abbaseya** [comment]
@mattddean yes, as long as node fetch is available, no harm using it 👌🏻

**Comment by abbaseya** [comment]
@mattddean your changes now released with js-sdk [v2.0.2](https://github.com/convertcom/javascript-sdk/releases/tag/js-sdk-v2.0.2) 🚀

**Comment by mattddean** [comment]
@abbaseya awesome!

**Pull request merged**
